### ISSUE TITLE
Since last update (1.9.4) some field randomly got a "display: block" breaking all my forms.

### ISSUE THREAD

**Issue by guilamu** [gravityforms/gravityforms#1]
Since last update (1.9.4) some field randomly got a "display: block" breaking all my forms. I had to go back to 1.9.3.1 to fix the issue.

**Comment by QuentinBellus** [comment]
Same issue, last update completely broke my forms. Restoring previous version did the trick. Can you guys fix the problem?

**Comment by dabernathy89** [comment]
FYI y'all this is not Rocketgenius's repo. Unless i'm mistaken, they do not publish the Gravity Forms source code publicly.
