### ISSUE TITLE
Bump to 1.9.13

### ISSUE THREAD

**Issue by haroldangenent** [gravityforms/gravityforms#6]
Version 1.9.10.15 is incompatible with WordPress 4.3, could use a version bump. Fixes are in 1.9.12, see https://www.gravityhelp.com/gravity-forms-v1-9-12-released/.

**Comment by ithinkdancan** [comment]
+1

**Comment by remcotolsma** [comment]
https://github.com/gravityforms/gravityforms/releases/tag/1.9.13.7
