### ISSUE TITLE
Why isn't this repository being updated?

### ISSUE THREAD

**Issue by rfair404** [gravityforms/gravityforms#7]
I use it to keep my site up to date, but it looks like updates aren't coming through. latest is 1.9.14.14 according to GF website.

**Comment by remcotolsma** [comment]
This repository is updated manually and only a few times per year.

**Comment by rfair404** [comment]
That's a bummer. It would seem like a fairly easy thing to keep up to date.

On Mon, Nov 2, 2015 at 9:18 AM, Remco Tolsma <notifications@github.com>
wrote:

> This repository is updated manually and only a few times per year.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gravityforms/gravityforms/issues/7#issuecomment-153028838>
> .
>



-- 
Thanks,

Russell Fair
770.401.9039

**Comment by brofar** [comment]
You're welcome to pay for the plugin and get instant updates. This person
is doing us all a favor, they don't owe us anything.

**Comment by rfair404** [comment]
I do pay for a developer license. I just prefer to use git for managing
plugins instead of having to manually download and update them all the
time. If the repo isn't going to be kept up to date then it is pretty much
useless, IMHO.

On Mon, Nov 2, 2015 at 9:57 AM, brofar <notifications@github.com> wrote:

> You're welcome to pay for the plugin and get instant updates. This person
> is doing us all a favor, they don't owe us anything.
> On Nov 2, 2015 7:53 AM, "Russell Fair" <notifications@github.com> wrote:
>
> > That's a bummer. It would seem like a fairly easy thing to keep up to
> date.
> >
> > On Mon, Nov 2, 2015 at 9:18 AM, Remco Tolsma <notifications@github.com>
> > wrote:
> >
> > > This repository is updated manually and only a few times per year.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/gravityforms/gravityforms/issues/7#issuecomment-153028838
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Thanks,
> >
> > Russell Fair
> > 770.401.9039
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/gravityforms/gravityforms/issues/7#issuecomment-153041422
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gravityforms/gravityforms/issues/7#issuecomment-153042824>
> .
>



-- 
Thanks,

Russell Fair
770.401.9039

**Comment by brofar** [comment]
Sorry, I'm new to github, but if you have a licence, can't you update it?

**Comment by rfair404** [comment]
sure if I want to log into gravityforms, save the zip file, merge it into
my project and then sync up. of course. but if the repo was "actually" a
mirror as the description claims, then all I would need to do would be
fetch the latest tag.

On Mon, Nov 2, 2015 at 10:08 AM, brofar <notifications@github.com> wrote:

> Sorry, I'm new to github, but if you have a licence, can't you update it?
>
> On Nov 2, 2015 8:06 AM, "Russell Fair" <notifications@github.com> wrote:
>
> > I do pay for a developer license. I just prefer to use git for managing
> > plugins instead of having to manually download and update them all the
> > time. If the repo isn't going to be kept up to date then it is pretty
> much
> > useless, IMHO.
> >
> > On Mon, Nov 2, 2015 at 9:57 AM, brofar <notifications@github.com> wrote:
> >
> > > You're welcome to pay for the plugin and get instant updates. This
> person
> > > is doing us all a favor, they don't owe us anything.
> > > On Nov 2, 2015 7:53 AM, "Russell Fair" <notifications@github.com>
> wrote:
> > >
> > > > That's a bummer. It would seem like a fairly easy thing to keep up to
> > > date.
> > > >
> > > > On Mon, Nov 2, 2015 at 9:18 AM, Remco Tolsma <
> notifications@github.com
> > >
> > > > wrote:
> > > >
> > > > > This repository is updated manually and only a few times per year.
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > > >
> > >
> >
> https://github.com/gravityforms/gravityforms/issues/7#issuecomment-153028838
> > > > >
> > > > > .
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > Thanks,
> > > >
> > > > Russell Fair
> > > > 770.401.9039
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/gravityforms/gravityforms/issues/7#issuecomment-153041422
> > > >
> > >
> > > > .
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/gravityforms/gravityforms/issues/7#issuecomment-153042824
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Thanks,
> >
> > Russell Fair
> > 770.401.9039
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/gravityforms/gravityforms/issues/7#issuecomment-153044991
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gravityforms/gravityforms/issues/7#issuecomment-153046349>
> .
>



-- 
Thanks,

Russell Fair
770.401.9039

**Comment by brofar** [comment]
Oh, I meant update the repo, but I guess that would be the same issue, hey?

**Comment by rfair404** [comment]
yeah I just submitted a PR -
https://github.com/gravityforms/gravityforms/pull/8


On Mon, Nov 2, 2015 at 10:17 AM, brofar <notifications@github.com> wrote:

> Oh, I meant update the repo, but I guess that would be the same issue, hey?
>
> On Nov 2, 2015 8:10 AM, "Russell Fair" <notifications@github.com> wrote:
>
> > sure if I want to log into gravityforms, save the zip file, merge it into
> > my project and then sync up. of course. but if the repo was "actually" a
> > mirror as the description claims, then all I would need to do would be
> > fetch the latest tag.
> >
> > On Mon, Nov 2, 2015 at 10:08 AM, brofar <notifications@github.com>
> wrote:
> >
> > > Sorry, I'm new to github, but if you have a licence, can't you update
> it?
> > >
> > > On Nov 2, 2015 8:06 AM, "Russell Fair" <notifications@github.com>
> wrote:
> > >
> > > > I do pay for a developer license. I just prefer to use git for
> managing
> > > > plugins instead of having to manually download and update them all
> the
> > > > time. If the repo isn't going to be kept up to date then it is pretty
> > > much
> > > > useless, IMHO.
> > > >
> > > > On Mon, Nov 2, 2015 at 9:57 AM, brofar <notifications@github.com>
> > wrote:
> > > >
> > > > > You're welcome to pay for the plugin and get instant updates. This
> > > person
> > > > > is doing us all a favor, they don't owe us anything.
> > > > > On Nov 2, 2015 7:53 AM, "Russell Fair" <notifications@github.com>
> > > wrote:
> > > > >
> > > > > > That's a bummer. It would seem like a fairly easy thing to keep
> up
> > to
> > > > > date.
> > > > > >
> > > > > > On Mon, Nov 2, 2015 at 9:18 AM, Remco Tolsma <
> > > notifications@github.com
> > > > >
> > > > > > wrote:
> > > > > >
> > > > > > > This repository is updated manually and only a few times per
> > year.
> > > > > > >
> > > > > > > —
> > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > <
> > > > > >
> > > > >
> > > >
> > >
> >
> https://github.com/gravityforms/gravityforms/issues/7#issuecomment-153028838
> > > > > > >
> > > > > > > .
> > > > > > >
> > > > > >
> > > > > >
> > > > > >
> > > > > > --
> > > > > > Thanks,
> > > > > >
> > > > > > Russell Fair
> > > > > > 770.401.9039
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > <
> > > > >
> > > >
> > >
> >
> https://github.com/gravityforms/gravityforms/issues/7#issuecomment-153041422
> > > > > >
> > > > >
> > > > > > .
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > > >
> > >
> >
> https://github.com/gravityforms/gravityforms/issues/7#issuecomment-153042824
> > > > >
> > > > > .
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > Thanks,
> > > >
> > > > Russell Fair
> > > > 770.401.9039
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/gravityforms/gravityforms/issues/7#issuecomment-153044991
> > > >
> > >
> > > > .
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/gravityforms/gravityforms/issues/7#issuecomment-153046349
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Thanks,
> >
> > Russell Fair
> > 770.401.9039
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/gravityforms/gravityforms/issues/7#issuecomment-153047765
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gravityforms/gravityforms/issues/7#issuecomment-153050009>
> .
>



-- 
Thanks,

Russell Fair
770.401.9039
